ci(k8s): introduce skaffold for managing development with hot reloading
feat(service): add api-data service

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,6 +23,8 @@ jobs:
       auth-ui--tag_name: ${{ steps.release-step.outputs['service/auth-ui--tag_name'] }}
       auth-token-exchange--release_created: ${{ steps.release-step.outputs['service/auth-token-exchange--release_created'] }}
       auth-token-exchange--tag_name: ${{ steps.release-step.outputs['service/auth-token-exchange--tag_name'] }}
+      api-data--release_created: ${{ steps.release-step.outputs['service/api-data--release_created'] }}
+      api-data--tag_name: ${{ steps.release-step.outputs['service/api-data--tag_name'] }}
 
     steps:
       - uses: googleapis/release-please-action@v4
@@ -44,6 +46,12 @@ jobs:
           echo "debug service/auth-ui path outputs:"
           echo "${{ steps.release-step.outputs['service/auth-ui--release_created'] }}"
           echo "${{ steps.release-step.outputs['service/auth-ui--tag_name'] }}"
+          echo "debug service/auth-token-exchange path outputs:"
+          echo "${{ steps.release-step.outputs['service/auth-token-exchange--release_created'] }}"
+          echo "${{ steps.release-step.outputs['service/auth-token-exchange--tag_name'] }}"
+          echo "debug service/api-data path outputs:"
+          echo "${{ steps.release-step.outputs['service/api-data--release_created'] }}"
+          echo "${{ steps.release-step.outputs['service/api-data--tag_name'] }}"
 
   web-server-publish-package:
     needs: [release-please]
@@ -318,6 +326,73 @@ jobs:
           EOF
           )
           gh release edit ${{ needs.release-please.outputs.auth-token-exchange--tag_name }} --notes "$new_desc"
+        env:
+          GITHUB_TOKEN: ${{secrets.PAT_WORKFLOW}}
+
+  api-data-publish-package:
+    needs: [release-please]
+    if: ${{ needs.release-please.outputs.api-data--release_created }}
+    permissions:
+      contents: write
+    strategy:
+      fail-fast: false
+
+    runs-on: "ubuntu-latest"
+
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./service/api-data
+
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      # find release ID given the associated tag and pass it to Tauri build in following step (bc it seems like tauri-action fails to find the release id sometimes)
+      - name: Find Release ID
+        id: find_release_id
+        env:
+          GITHUB_TOKEN: ${{secrets.PAT_WORKFLOW}}
+        run: |
+          release_id=$(gh release view ${{ needs.release-please.outputs.api-data--tag_name }} --json databaseId | jq -r '.databaseId')
+          echo "release_id=$release_id" >> $GITHUB_OUTPUT
+          if [[ -z "$release_id" ]]; then
+            echo "Error: release id retrieval failed for tagname: ${{ needs.release-please.outputs.api-data--tag_name }}"
+            exit 1;
+          else 
+            echo "release_id=$release_id"
+          fi
+
+      - name: build api-data container
+        working-directory: ./service/api-data
+        run: |
+          chmod +x ./script.sh
+          ./script.sh build_container_api_data production
+
+      - name: upload container to Github Container Registry
+        run: |
+          echo "${{ secrets.PAT_GITHUB_CONTAINER_REGISTRY }}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
+          TAG=api-data:latest
+          docker tag $TAG ghcr.io/szn-app/donation-app/$TAG
+          docker push ghcr.io/szn-app/donation-app/$TAG
+          VERSION_TAG=${{ needs.release-please.outputs.api-data--tag_name }}
+          MAPPED_VERSION="${VERSION_TAG//@/:}"
+          docker tag $TAG ghcr.io/szn-app/donation-app/$MAPPED_VERSION
+          docker push ghcr.io/szn-app/donation-app/$MAPPED_VERSION
+
+      - name: Update release description
+        run: |
+          release_desc=$(gh release view ${{ needs.release-please.outputs.api-data--tag_name }} --json body | jq -r '.body')
+          new_desc=$(cat <<EOF
+          $release_desc
+          ___
+          ### Container:
+          * [api-data:latest](https://ghcr.io/szn-app/donation-app/api-data:latest)
+          EOF
+          )
+          gh release edit ${{ needs.release-please.outputs.api-data--tag_name }} --notes "$new_desc"
         env:
           GITHUB_TOKEN: ${{secrets.PAT_WORKFLOW}}
         
